### ISSUE TITLE
[APP-37] INSTALL.txt Please

### ISSUE THREAD

**Issue by mgifford** [jptrsn/zip-captions#18]
<p>Would be great to have some basic installation instructions to get folks going and have that linked from the README.</p>

**Comment by jptrsn** [comment]
Great idea! Any specific sections you're looking for, or just general "clone the repo, follow these steps to get started" kind of thing? If you have an example you'd like to see reproduced here, reply with a link and I'll do my best.

**Comment by mgifford** [comment]
Just the basic one to get going.  

I don't have an example, but how would you explain to someone how to get started?

**Comment by jptrsn** [comment]
Get started using the app, or get started developing with it?

**Comment by mgifford** [comment]
I usually start with using the app. Then I can see how I might want to do things differently. Finally, I hope to find things I can contribute back to the community. 

I have to first get a local install going though.

**Comment by jptrsn** [comment]
File is merged down to `main` branch.
