### ISSUE TITLE
[APP-82] Speech Recognition Error: Speech Input Was Aborted In Some Manner.

### ISSUE THREAD

**Issue by HobbySquig** [jptrsn/zip-captions#56]
<p>I'm getting a persistent error: whilst speaking after a few seconds this pops up and the input stops completely until I double click the microphone button (it then does it again a few seconds later). 
Browser: Google Chrome
Have tried clearing browser cache, running in incognito window, restarting audio engine, using alternative audio inputs (both through my virtual audio engine and not)</p>

**Comment by jptrsn** [comment]
Thanks for reporting this issue. I will attempt to reproduce the problem, and may reply here asking you to test or provide additional information. Adding info from discord here for more info:

> OS: Windows 11 (new hardware, not going to be an issue)
> Browser: Google Chrome (version unknown) - bug persists in incognito session
> Audio input device: Local mic
> Other software: voice meeter

**Comment by jptrsn** [comment]
Unfortunately, I do not have access to a Windows computer. However, in testing on Linux with Pulsemeeter (a voicemeeter alternative), it appears to have a conflict with the browser's microphone access and ability to send data to the speech recognition service.

Currently, I think the best solution would be to access zipcaptions on a separate device and streaming the results to the machine running voicemeeter.

We may be able to work around this issue in future, but for now, as this is a conflict between the browser API and the local machine's hardware, I am unable to provide a solution.
