### ISSUE TITLE
Repeating speech recognition and network communication errors

### ISSUE THREAD

**Issue by TheRealPear** [jptrsn/zip-captions#90]
**Describe the bug**
When I use Zip Captions for a lecture at a college class, it will repeatedly stop transcribing and give a speech recognition error stating the required network communication for completing the recognition has failed. This only occurs through basic listening as I do not use the sharing/broadcast feature.

**To Reproduce**
1. Go to Google Chrome, visit https://zipcaptions.app/
2. Click on the microphone (🎤) icon in the top-right corner.
3. Transcribed audio will appear and works for certain amount of time.
4. The error (in red text) will appear and the microphone (🎤) icon in the top-right corner becomes a warning (⚠️) symbol. When hovering over the warning symbol, a yellow tooltip appears saying `Network`.

**Expected behavior**
Zip Captions should continue to transcribe as normal, as long there is no issue with Google's speech recognition service.

**Actual behavior**
At random interval, Zip Captions will stop transcribing and give me an error, *Speech recognition error: Network communication required for completing the recognition failed.* Sometimes it is not clear an error has occurred as it is usually hidden towards the top instead of appearing at the bottom for me to easily see.

**Screenshots**
<details>
    <summary>Screenshots from 1/22/2024 Discord discussion</summary>

![error1](https://github.com/jptrsn/zip-captions/assets/20259871/75744198-54a0-4817-a511-a94f84d9cc08)
![error2](https://github.com/jptrsn/zip-captions/assets/20259871/46839bbe-4d07-4ccd-b84f-cde8161b1c6c)
![error3](https://github.com/jptrsn/zip-captions/assets/20259871/24c56b2d-bbd9-49dc-b547-78dfea20645c)

</details>

<details>
    <summary>1/24/2024 DevTools network log</summary>

![image](https://github.com/jptrsn/zip-captions/assets/20259871/4ec600a1-aa56-4c4a-af31-0b0dbe8274e8)

</details>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 120.0.6099.227
 - Microphone: built into a HP all-in-one system, can get more information if necessary

**Additional context**
I was directed here after a brief discussion in the #bugs channel of the Discord server.

**Comment by jptrsn** [comment]
Thank you for reporting the bug, this is really helpful info! I have everything I need in order to reproduce and fix this issue, it has been added to the roadmap.

**Comment by jptrsn** [comment]
I have a provisional solution that I am testing now. If it passes, you can expect a release at some point this week that should hopefully improve this situation.

**Comment by jptrsn** [comment]
We have released the fix that should address the problem you're experiencing. The app will now attempt to reconnect for up to 3 seconds before erroring out, so it should be able to re-establish a connection to the recognition server. Depending on how much time that takes, you may notice it drops a word or two during the period of disconnection, but that depends on how your network behaves, server connection latency, and other factors which I cannot reproduce locally.

I hope it fixes the problem and allows you to more easily use Zip Captions for your lectures. Thanks so much for your patience while we addressed the problem.
