### ISSUE TITLE
Application affecting mic control on pc

### ISSUE THREAD

**Issue by Grizz1yBear** [jptrsn/zip-captions#99]
When using the application on its webpage, it is affecting microphone levels on the PC. 
It is choosing the levels that the microphone reads out without someone changing it or wanting it to be changed. 

to reproduce:
Open up the zipcaptions
open up sounds on pc
open up properties of microphone
Go to levels section of microphone
once you start to have zip captions listening, it will change the volume levels

**Expected behavior**
Expected to capture words and produce captions but not change the volume of my microphone as it is used elsewhere.

**Actual behavior**
It is changing the levels of my microphone

**Screenshots**
![before starting zipcaptionws](https://github.com/jptrsn/zip-captions/assets/163496460/2d8a10db-bd12-44c4-9f99-6d56ca216a38)
![after starting zip captions](https://github.com/jptrsn/zip-captions/assets/163496460/a23a2a96-604a-4910-b58c-9584f1f3e281)

**Desktop (please complete the following information):**
 - OS: 64-bit Windows 10 Home
 - Browser Chrome
 - Version 22H2

**Additional context**
This was not happening just a couple weeks ago, not sure why it is now connected to change volume levels. If this is an added feature it would be nice to be removed. It is changing my microphone levels to random amounts. As a streamer I need these to stay at the same level unless I am changing them. Thank you for looking into this

**Comment by Grizz1yBear** [comment]
Problem has been fixed

go here to see solution:
https://help.zipcaptions.app/knowledge_base/kb_2.html

**Comment by jptrsn** [comment]
Thank you for posting the solution. :)
